# Generated by Django 5.1.4 on 2025-04-06 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_genre_alter_genres_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Subscription',
        ),
    ]
