# Generated by Django 5.1.4 on 2025-04-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_genres_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='', max_length=255),
        ),
    ]
